/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Click Powers': '点击威力',
    'Rainbow x50': '彩虹 x50',
    'Rainbow sells for $500k each': '每个彩虹售价 50 万美元',
    'Ruby': '红宝石',
    'Buy the sapphire clickpower': '购买蓝宝石点击力量',
    'Buy the topaz clickpower': '购买黄玉点击力量',
    'Collected a buff': '收集 1 个增益',
    'DIAMONDS!': '钻石！',
    'Diamond': '钻石',
    'Double Rainbow': '双重彩虹',
    'Do you even lift?': '你有做重量训练吗？',
    'DROP': '掉落',
    'Gym rat': '健身房老鼠',
    'Green Thumb': '绿拇指',
    'Hard reset': '硬复位',
    'Hello world': '你好世界',
    'Hello World': '你好世界',
    'Import game': '导入存档',
    'Buy a quartz factory': '购买1个 石英 工厂',
    'Buy a sapphire factory': '购买1个 蓝宝石 工厂',
    'Buy an emerald factory': '购买1个 翡翠 工厂',
    'Buy an amethyst factory': '购买1个 紫水晶 工厂',
    'Buy a topaz factory': '购买1个 黄玉 工厂',
    'Buy a ruby factory': '购买1个 红宝石 工厂',
    'Buy a rainbow factory': '购买1个 彩虹 工厂',
    'Quartz': '石英',
    'Quartz Factory': '石英工厂',
    'Quartz Mogul': '石英大亨',
    'Quartz Quarry': '石英采石场',
    'Rainbow Factory': '彩虹工厂',
    'Quartz sell price doubled': '石英售价翻倍',
    'Quartz sells for $1 each': '石英每个售价 $1',
    'Owned Upgrades': '已拥有升级',
    'Overseer': '监工',
    'Popup text goes here': '弹出文本到这里',
    'MAX': '最大',
    'Max out the inventory': '大化库存',
    'Middle-Class': '中产阶级',
    'More Buffs': '更多增益',
    'More space to hold gems.': '更多的空间来放置宝石。',
    'My First Upgrade': '我的第一次升级',
    'Keep the gate open permanently.': '永远保持大门敞开。',
    'Lucy in the Sky': '天空中的露西',
    'Opulent': '富丽堂皇',
    'Open the Floodgates': '打开闸门',
    'One week of total playtime': '一周的总游戏时间',
    'Obscene': '猥琐',
    'Meta-Meta-Achievement': '元-元成就',
    'Rainbow': '彩虹',
    'Rainbow sell price doubled': '彩虹售价翻倍',
    'Red Handed': '红手',
    'Reimbursement': '退还',
    'Gems lost': '宝石丢失',
    'Export game': '导出存档',
    'Factories': '工厂',
    'Gems dropped': '掉落的宝石',
    'Gems spawned by clicking': '通过点击产生的宝石',
    'Upgrades': '升级',
    'Upgrade x25': '升级 x25',
    'Upgrade to 100% autodrop': '升级到 100% 自动掉落',
    'Unlock every achievement': '解锁每一个成就',
    'View Owned Upgrades': '查看已拥有升级',
    'Wealthy': '富裕',
    'What does it mean?': '这是什么意思？',
    'Why can\'t I hold all these gems?': '为什么我不能持有所有这些宝石？',
    'Topaz': '黄玉',
    'Time played': '游戏时长',
    'The Blues': '蓝调',
    'Three points where two lines meet': '两条线相交的三个点',
    'Topaz Toucher': '黄玉触摸',
    'Topaz Tycoon': '黄玉大亨',
    'Buffs': '增益',
    'Buffer Overflow': '增益溢出',
    'Buffs are automatically collected when they are dropped.': '掉落时会自动收集增益。',
    'Buffs randomly spawn (about once every 20 seconds). Click on a buff to collect it.': '增益随机产生（大约每 20 秒一次）。 点击一个增益来收集它。',
    'Buffs spawn more often (about once every 10 seconds).': '增益产生的频率更高（大约每 10 秒一次）。',
    'BUY': '购买',
    'Blue Skies': '蓝天',
    'Bejewelled': '珠光宝气',
    'Autosave': '自动保存',
    'Amethyst x50': '紫水晶 x50',
    'Amethyst sells for $75 each': '紫水晶每颗售价 $75',
    'Spillage': '溢出',
    'Stacked': '堆叠',
    'Stats': '统计',
    'Sell a factory': '出售一个工厂',
    'SELL': '出售',
    'Seeing Red': '看到红色',
    'Secret red text': '秘密红色文字',
    'Script kiddie': '脚本小子',
    'Save game': '保存游戏',
    'Saves game in real time': '实时保存游戏',
    'Schwarzenegger': '施瓦辛格',
    'Sapphire Supplier': '蓝宝石供应商',
    'Alternatively: Introduction to the Developer Console.': '或者：开发者控制台简介。',
    'Amethyst': '紫水晶',
    'Amethyst Amateur': '紫水晶业余爱好者',
    'Amethyst Automation': '紫水晶自动化',
    'Amethyst Factory': '紫水晶工厂',
    'Amethyst sell price doubled': '紫水晶售价翻倍',
    'Buff Autocollect': '增益自动收集',
    'Buff AF': '增益AF',
    'Buffed': '增益',
    '[close]': '[关闭]',
    '50% sell price for 15 seconds': '50% 售价 15 秒',
    '7-Fingered Man': '七指人',
    'Buy all upgrades': '购买全部升级',
    'Buy an upgrade': '购买1个升级',
    'Buy the amethyst clickpower': '购买 紫水晶 点击威力',
    'Buy the diamond clickpower': '购买 钻石 点击威力',
    'Buy the emerald clickpower': '购买 翡翠 点击威力',
    'Buy the rainbow clickpower': '购买 彩虹 点击威力',
    'Buy the ruby clickpower': '购买 红宝石 点击威力',
    'Buy all 7 clickpowers': '购买全部7种点击威力',
    'Buy a diamond factory': '购买 1个 钻石工厂',
    'Emerald': '翡翠',
    'Delete all saved data': '删除全部存档',
    'Diamond Factory': '钻石工厂',
    'Diamond Miner': '钻石矿工',
    'Diamond sell price doubled': '钻石出售价格翻倍',
    'Diamond sells for $75k each': '钻石每颗售价 $75k',
    'Diversifying Your Portfolio': '多样化您的投资组合',
    'Emerald Engineer': '翡翠工程师',
    'Emerald Enthusiast': '翡翠爱好者',
    'Emerald Entrepreneur': '翡翠企业家',
    'Emerald Factory': '翡翠工厂',
    'Emerald sell price doubled': '翡翠售价翻倍',
    'Emerald sells for $2.5k each': '翡翠每颗售价 $2.5k',
    'except this one': '除了这个',
    'Floating numbers': '浮点数',
    'Heart': '心',
    'Hold down the mouse button to continuously spawn gems for 10 seconds': '按住鼠标按钮连续产生宝石 10 秒',
    'Jazz Hands': '爵士之手',
    'Last saved less than a second ago': '上次保存不到一秒前',
    'Leprechaun': '妖精',
    'Or is it gem rat?': '还是宝石鼠？',
    'Outrageous': '离谱',
    'Overachiever': '成就者',
    'Purple Haze': '紫色雾团',
    'Quartz sells for $2 each': '石英每个售价 $2',
    'Copy the following code to a text file': '将以下代码复制到文本文件中',
    'Triangles are my favorite shape': '三角形是我最喜欢的形状',
    'Truly, truly, TRULY outrageous.': '真的，真的，真的很离谱。',
    'Unlock 4 meta-achievements': '解锁 4 个元成就',
    'You killed my father. Prepare to die.': '你杀了我父亲。 准备去死。',
    'Lose a gem when it falls outside the inventory': '当宝石落在物品栏之外时失去它',
    'Render Sprites': '渲染精灵',
    'Ruby x50': '红宝石 x50',
    'Ruby Factory': '红宝石工厂',
    'Ruby Producer': '红宝石生产者',
    'Ruby sell price doubled': '红宝石出售价格翻倍',
    'Ruby sells for $15k each': '红宝石单价 $15k',
    'Sapphic Love': '蓝宝石之恋',
    'Sapphire': '蓝宝石',
    'Sapphire Factory': '蓝宝石工厂',
    'Sapphire sell price doubled': '蓝宝石售价翻倍',
    'Sapphire sells for $500 each': '蓝宝石单价 $500',
    'Sick gains': '病态收益',
    'So much space for activities': '这么多活动空间',
    'Spawn a gem by clicking': '点击生成 1 颗宝石',
    'Spawn twice as many gems by clicking for 5 seconds': '点击 5 秒可生成两倍的宝石',
    'Star': '星星',
    'Teardrop': '泪珠',
    'Topaz Factory': '黄玉工厂',
    'Topaz sell price doubled': '黄玉售价翻倍',
    'Topaz sells for $10 each': '黄玉单价 $10',
    'Topaz x50': '黄玉 x50',
    'Total money earned': '总收入',
    '1 day of total playtime': '1 天总游戏时间',
    '1 hour of total playtime': '1 小时总游戏时间',
    '1 each': '1 每个',
    '1 per click': '1 每次点击',
    '1 topaz per click': '1 黄玉每次点击',
    '200% factory production for 10 seconds': '200% 工厂产量 持续 10 秒',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Costs $": "成本 $",
    "Click x": "点击 x",
    "$": "$",
    "(+": "(+",
    "Rainbow Value": "彩虹价值",
    "Gem Dropper": "宝石掉落器",
    "Make ": "赚取",
    "Meta-Achievement ": "元成就",
    "Quartz Value": "石英价值",
    "Lvl ": "等级 ",
    'Topaz Value': '黄玉价值',
    "Auto Drop": "自动掉落",
    "Amethyst Value": "紫水晶价值",
    "Sapphire Value": "蓝宝石价值",
    "Buy 1 for ": "购买 1 花费",
    "Diamond Value": "钻石价值",
    "Ruby Value": "红宝石价值",
    "Emerald Value": "翡翠价值",
    "Inventory Size": "库存大小",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " owned": " 拥有",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^\(\+(\d+)$/,
    /^(\d+)$/,
    /^成本 (.+)$/,
    /^(\d+)\:(\d+)\:(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Collected (.+) buffs$/, '收集 $1 个增益'],
    [/^Rainbow doubled again \((.+)x total$/, '彩虹再次翻倍（总共 $1 倍'],
    [/^Quartz doubled again \((.+)x total$/, '石英再次翻倍（总共 $1 倍'],
    [/^Emerald doubled again \((.+)x total$/, '翡翠再次翻倍（总共 $1 倍'],
    [/^Diamond doubled again \((.+)x total$/, '钻石再次翻倍（总共 $1 倍'],
    [/^Topaz doubled again \((.+)x total$/, '黄玉再次翻倍（总共 $1 倍'],
    [/^Ruby doubled again \((.+)x total$/, '红宝石再次翻倍（总共 $1 倍'],
    [/^Sapphire doubled again \((.+)x total$/, '蓝宝石再次翻倍（总共 $1 倍'],
    [/^Amethyst doubled again \((.+)x total$/, '紫水晶再次翻倍（总共 $1 倍'],
    [/^Automatically drops gems every (.+) seconds.$/, '每 $1 秒自动掉落宝石。'],
    [/^Unlock (.+) achievements$/, '解锁 $1 成就'],
    [/^Buy (.+) factories of every type$/, '购买 $1 各类工厂'],
    [/^Buy (.+) total factory$/, '累计购买 $1 工厂'],
    [/^Buy (.+) total factories$/, '累计购买 $1 工厂'],
    [/^Buy (.+) quartz factories$/, '购买 $1 石英工厂'],
    [/^Buy (.+) amethyst factories$/, '购买 $1 紫水晶工厂'],
    [/^Buy (.+) rainbow factories$/, '购买 $1 彩虹工厂'],
    [/^Buy (.+) emerald factories$/, '购买 $1 翡翠工厂'],
    [/^Buy (.+) topaz factories$/, '购买 $1 黄玉工厂'],
    [/^Buy (.+) diamond factories$/, '购买 $1 钻石工厂'],
    [/^Buy (.+) sapphire factories$/, '购买 $1 蓝宝石工厂'],
    [/^Buy (.+) ruby factories$/, '购买 $1 红宝石工厂'],
    [/^Buy (.+) amethyst factory$/, '购买 $1 紫水晶工厂'],
    [/^Buy (.+) topaz factory$/, '购买 $1 黄玉工厂'],
    [/^Buy (.+) emerald factory$/, '购买 $1 翡翠工厂'],
    [/^Buy (.+) sapphire factory$/, '购买 $1 蓝宝石工厂'],
    [/^Buy (.+) ruby factory$/, '购买 $1 红宝石工厂'],
    [/^Buy (.+) quartz factory$/, '购买 $1 石英工厂'],
    [/^Buy (.+) rainbow factory$/, '购买 $1 彩虹工厂'],
    [/^Buy (.+) upgrades$/, '购买 $1 升级'],
    [/^Drop (.+) gems$/, '掉落 $1 宝石'],
    [/^Lose (.+) gems when they fall outside the inventory$/, '当宝石落在物品栏之外时失去 $1 颗宝石'],
    [/^Spawn (.+) gems by clicking$/, '点击生成 $1 颗宝石'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+) amethyst per second$/, '$1 紫水晶每秒'],
	[/^([\d\.]+) ruby per second$/, '$1 红宝石每秒'],
	[/^([\d\.]+) sapphire per second$/, '$1 蓝宝石每秒'],
	[/^([\d\.]+) rainbow per second$/, '$1 彩虹每秒'],
	[/^([\d\.]+) quartz per second$/, '$1 石英每秒'],
	[/^([\d\.]+) emerald per second$/, '$1 翡翠每秒'],
	[/^([\d\.]+) diamond per second$/, '$1 钻石每秒'],
	[/^([\d\.]+) diamond per click$/, '$1 钻石每次点击'],
	[/^([\d\.]+) amethyst per click$/, '$1 紫水晶每次点击'],
	[/^([\d\.]+) ruby per click$/, '$1 红宝石每次点击'],
	[/^([\d\.]+) sapphire per click$/, '$1 蓝宝石每次点击'],
	[/^([\d\.]+) rainbow per click$/, '$1 彩虹每次点击'],
	[/^([\d\.]+) quartz per click$/, '$1 石英每次点击'],
	[/^([\d\.]+) emerald per click$/, '$1 翡翠每次点击'],
	[/^([\d\.]+) days of total playtime$/, '$1 天总计游戏时间'],
	[/^([\d\.]+) days$/, '$1 天'],
	[/^([\d\.]+) minutes$/, '$1 分钟'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);